name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Pack the Met.no Nowcast dir as a zip and upload to the release
      - name: ZIP Met.no Nowcast Dir
        run: |
          cd ${{ github.workspace }}/custom_components/metnowcast
          zip metnowcast.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/metnowcast/metnowcast.zip
          asset_name: metnowcast.zip
          tag: ${{ github.ref }}
          overwrite: true
